### PR TITLE
Jib 1.8.45

### PR DESCRIPTION
**Pull request by jib**
Elasticsearch needs java8 >= 1.8.25. The current stable is 1.8.45, and this branch adds it.

@sethyates, please double check that this upgrade is ok

### CODE REVIEW

**Comment by prashuj** [comment]
:+1:

**Comment by plathrop** [comment]
Closing due to lack of activity / bitrot.

**Comment by jib** [comment]
This should be re-opened and done. It's an outstanding task that ES would benefit from, but needs dev approval

**Comment by plathrop** [comment]
@jib nothing blocking that I am aware of.

**Comment by jib** [comment]
@sethyates, +1 please?

**Comment by sethyates** [comment]
:+1:

**Pull request merged**
